services:
  postgresql:
    image: postgres:15-alpine3.21
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  application:
    build: .
    depends_on:
      - postgresql
    ports:
      - "8080:8080"